name: CI Docker

on:
  push:
    tags:
      - dev/payment-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          PORT=${{ secrets.SSH_PORT }}
          HOST=${{ secrets.SSH_HOST }}
          ssh-keyscan -p "${PORT:-22}" "$HOST" >> ~/.ssh/known_hosts
  
      - name: Load Env
        id: load_env
        run: |
          ENV_CONTENT=$(ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cat /root/payment-service/.env')
          echo "ENV_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$ENV_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  
      - name: Build Docker Images and Save as TAR
        run: |
          mkdir -p images
          echo "${{ steps.load_env.outputs.ENV_CONTENT }}" > ./services/payment-service/.env
          echo "✅ .env file created locally:"
          cat ./services/payment-service/.env
          IMAGE_NAME=payment-service:latest
          echo "🛠️ Building $IMAGE_NAME"
          docker build -t $IMAGE_NAME --build-arg SERVICE_NAME=payment-service .
          docker save -o ./images/payment-service.tar $IMAGE_NAME
  
      - name: Copy Images to VPS
        run: |
          scp -P ${{ secrets.SSH_PORT }} ./images/payment-service.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/
  
      - name: Deploy Images on VPS
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          echo "📦 Loading image for payment-service..."
          docker load -i /tmp/payment-service.tar
          docker stop payment-service || true
          docker rm payment-service || true
          docker run -d --name payment-service --restart=unless-stopped --expose 8001 --network logistik_nginx_proxy_manager_default payment-service:latest  # Ganti port sesuai kebutuhan
          EOF
